# Copyright (c) 2025 anicatpro
# Author: anicatpro (Paul Afanasev)
# License: MIT

version: "3.8"
x-shared:
  zammad-service: &a1
    environment:
      MEMCACHE_SERVERS: zammad-memcached:11211
      POSTGRESQL_DB: zammad_production
      POSTGRESQL_HOST: zammad-postgresql
      POSTGRESQL_USER: zammad
      POSTGRESQL_PASS: zammad
      POSTGRESQL_PORT: "5432"
      POSTGRESQL_OPTIONS: ?pool=50
      REDIS_URL: redis://zammad-redis:6379
      S3_URL: null
      BACKUP_DIR: /var/tmp/zammad
      BACKUP_TIME: 03:00
      HOLD_DAYS: "10"
      TZ: Europe/Moscow
      ELASTICSEARCH_ENABLED: "true"
      ELASTICSEARCH_SCHEMA: http
      ELASTICSEARCH_HOST: zammad-elasticsearch
      ELASTICSEARCH_PORT: "9200"
      ELASTICSEARCH_USER: elastic
      ELASTICSEARCH_PASS: zammad
    image: ghcr.io/zammad/zammad:6.5.0-75 # Версия
    restart: always
    volumes:
      - zammad-storage:/opt/zammad/storage
    depends_on:
      - zammad-memcached
      - zammad-postgresql
      - zammad-redis
services:
  zammad-backup:
    <<: *a1
    command:
      - zammad-backup
    volumes:
      - zammad-backup:/var/tmp/zammad
      - zammad-storage:/opt/zammad/storage:ro
    user: 0:0
  zammad-elasticsearch:
    image: bitnami/elasticsearch:8.18.0
    restart: always
    volumes:
      - elasticsearch-data:/bitnami/elasticsearch/data
    environment:
      ELASTICSEARCH_ENABLE_SECURITY: "true"
      ELASTICSEARCH_SKIP_TRANSPORT_TLS: "true"
      ELASTICSEARCH_ENABLE_REST_TLS: "false"
      ELASTICSEARCH_PASSWORD: zammad
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      cluster.routing.allocation.disk.watermark.low: 1gb
      cluster.routing.allocation.disk.watermark.high: 500mb
      cluster.routing.allocation.disk.watermark.flood_stage: 200mb
      cluster.info.update.interval: 1m
    ulimits:
      memlock:
        soft: 262144
        hard: 262144
    mem_limit: 1500m
  zammad-init:
    <<: *a1
    command:
      - zammad-init
    depends_on:
      - zammad-postgresql
    restart: on-failure
    user: 0:0
  zammad-memcached:
    command: memcached -m 256M
    image: memcached:1.6.38-alpine
    restart: always
  zammad-nginx:
    <<: *a1
    command:
      - zammad-nginx
    expose:
      - "8080"
    ports:
      - 8080:8080
    depends_on:
      - zammad-railsserver
  zammad-postgresql:
    environment:
      POSTGRES_DB: zammad_production
      POSTGRES_USER: zammad
      POSTGRES_PASSWORD: zammad
    image: postgres:17.5-alpine
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  zammad-railsserver:
    <<: *a1
    command:
      - zammad-railsserver
  zammad-redis:
    image: redis:7.4.3-alpine
    restart: always
    volumes:
      - redis-data:/data
  zammad-scheduler:
    <<: *a1
    command:
      - zammad-scheduler
  zammad-websocket:
    <<: *a1
    command:
      - zammad-websocket
volumes:
  elasticsearch-data:
    driver: local
  postgresql-data:
    driver: local
  redis-data:
    driver: local
  zammad-backup:
    driver: local
  zammad-storage:
    driver: local